### ISSUE TITLE
install script fails with `xhyve` driver on macOS

### ISSUE THREAD

**Issue by xcoulon** [openshift-cloud-functions/knative-operators#31]
When running the `etc/install-on-minishift.sh` script on macOS, I get the following error:
````
./etc/scripts/install-on-minishift.sh
+ OPENSHIFT_VERSION=v3.11.0
+ MEMORY=10GB
+ CPUS=4
+ DISK_SIZE=50g
+ minishift profile delete knative --force
Profile 'knative' deleted successfully.
Switching to default profile 'minishift' as the active profile.
+ minishift profile set knative
Profile 'knative' set as active profile.
+ minishift config set openshift-version v3.11.0
+ minishift config set memory 10GB
No Minishift instance exists. New 'memory' setting will be applied on next 'minishift start'
+ minishift config set cpus 4
No Minishift instance exists. New 'cpus' setting will be applied on next 'minishift start'
+ minishift config set disk-size 50g
No Minishift instance exists. New 'disk-size' setting will be applied on next 'minishift start'
+ minishift config set image-caching true
+ minishift addons enable admin-user
Add-on 'admin-user' enabled
+ minishift start
-- Starting profile 'knative'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ... FAIL
   See the 'Setting Up the Virtualization Environment' topic (https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html) for more information
````
I wonder if the script should rather use `hyperkit` as it seems the be the preferred VM driver upstream: https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#hyperkit-driver.

Having `hyperkit` already installed on my machine, I just needed to add the following line:
````
minishift config set vm-driver hyperkit
````

**Comment by rhuss** [comment]
For both, `hyperkit` and `xhyve` you have some pre-requisites:

* `hyperkit`: 
  - [minikube](https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#hyperkit-driver)
  - [minishift](https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html#setting-up-hyperkit-driver)
  - Or you have the Docker Desktop for Mac installed
* `xhyve`: 
  - [minishift](https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html#setting-up-xhyve-driver)

But you are right, xhyve is deprecated in favor of hyperkit, so we should switch to hyperkit as the default VM. Minikube even has already removed its installation instructions for xhyve.
