### ISSUE TITLE
support to choose components

### ISSUE THREAD

**Issue by kameshsampath** [openshift-cloud-functions/knative-operators#47]
it will be nice to have the CLI option to choose the components that we wish to install. Right now we install serving, build and eventing, lets say i want only serving then the CLI option to choose helps.

**Comment by bbrowning** [comment]
We're getting rid of the install.sh script entirely (and deprecating this repo) soon. Then you'll just install the individual Operators, either via OLM or an `oc apply` of each. Does that work for your use-case here?
