### ISSUE TITLE
Latest operator does not bring up the in-memory-dispatcher

### ISSUE THREAD

**Issue by matzew** [openshift-cloud-functions/knative-operators#5]
Running the `./etc/scripts/install.sh` from master, where sources/eventing are in `knative-eventing` ns, I do not see the `dispatcher` for the `in-mem` channel

oc get pods:

```
...
eventing-controller-8d4cf7645-thgb8             1/1       Running   0          1m
in-memory-channel-controller-665d88c6d7-rxgdj   1/1       Running   0          1m
webhook-776475bb76-hz78k                        1/1       Running   0          1m
```

In the minishift-addon for eventing, we grant some permissions for the dispatcher, e.g.:
* https://github.com/openshift-cloud-functions/minishift-addons/blob/master/knative-eventing/eventing.addon#L19
* https://github.com/openshift-cloud-functions/minishift-addons/blob/master/knative-eventing/eventing.addon#L28

granting those, and (re)applying the `eventing` (just core), gives me the missing pod:

```
...
eventing-controller-5d899b5c58-8xs9p            1/1       Running   0          1m
in-memory-channel-controller-665d88c6d7-ld4cx   1/1       Running   0          59s
in-memory-channel-dispatcher-7678744794-tnklt   2/2       Running   1          58s
webhook-776475bb76-c7ktb                        1/1       Running   0          1m
```

**Comment by jcrossley3** [comment]
Fixed by 2a52259d9
